name: Development build

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build_unity:
    name: Build ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS
    
    steps:
      # Actionsがリポジトリにアクセスできるようにする
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # LibraryをCacheしてBuildを高速化する
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**','ProjectSettings/**') }}
          restore-keys:
            Library-
            
      # MacOS Buildする
      - name: Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Custom
          version: 0.1.${{ github.run_number }}
          
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
