name: Development build

# このworkflowを実行するトリガー
on:
# push: {}
  workflow_dispatch: {}

# 実行する中身
jobs:
  build_unity:
    name: Build ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**','ProjectSettings/**') }}
          restore-keys:
            Library-

      - name: Build Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Custom
          version: 0.1.${{ github.run_number }}

      - name: Upload [xcodeproj]   
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  # xcodeprojビルド
  build_xcode:
    runs-on: macos-latest
    needs: build_unity
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATES_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          CERTIFICATES_PASSWORD: ${{ secrets.P12_PASSWORD }}
          CERTIFICATES_PATH: ${{ format('{0}/Certificates.p12', github.workspace) }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          KEYCHAIN_PATH: ${{ format('{0}/app-signing.keychain-db', github.workspace) }}
          MOBILEPROVISION_PATH: ${{ format('{0}/Target.mobileprovision', github.workspace) }}
        run: |
          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATES_BASE64" | base64 --decode -o $CERTIFICATES_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $MOBILEPROVISION_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATES_PATH -P "$CERTIFICATES_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $MOBILEPROVISION_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Download [xcodeproj]
        uses: actions/download-artifact@v4
        with:
          name: Build-iOS
          path: build/iOS


      - name: Build Xcode
        uses: maierj/fastlane-action@v2.0.0
        env:
          MOBILEPROVISION_PATH: ${{ format('{0}/Target.mobileprovision', github.workspace) }}
          IPA_OUTPUT_PATH: ${{ format('{0}/Output/A4cselAR.ipa', github.workspace) }}
          IOS_BUILD_PATH: ${{ format('{0}/build/iOS', github.workspace) }}
          IOS_APP_ID: ${{ secrets.BUNDLE_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          CERTIFICATES_PATH: ${{ format('{0}/Certificates.p12', github.workspace) }}
          CERTIFICATES_PASSWORD: ${{ secrets.P12_PASSWORD }}
        with:
          lane: 'ios development'

      - name: upload ipa
        uses: actions/upload-artifact@v4
        with:
          name: Build-iOS-ipa
          path: ${{ format('{0}/Output', github.workspace) }}

      - name: Cleanup
        if: always()
        uses: geekyeggo/delete-artifact@v1
        with:
          name: Build-iOS

    
