name: MacOS Build
# コードがmainにpushされた時とpullreqが飛んできた時に自動で実行し手動でも実行できるようにする

on:
#  push:
#    branches: main
  workflow_dispatch: {}

jobs:
  unity-Build:
    name: Run the unity build steps
    runs-on: macos-latest
    steps:
      # Actionsがリポジトリにアクセスできるようにする
      - name: Checkout
        uses: actions/checkout@v4
      
      # LibraryをCacheしてBuildを高速化する
      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**','ProjectSettings/**') }}
          restore-keys: Library-
      # MacOS Buildする
      - name: Run the MacOS build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: iOS
          unityVersion: 2022.3.30f1
          buildName: A4cselAR
      # Build成果物をアップロードする
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
